version: 2.1

jobs:
  build: 
    docker:
      - image: golang:1.17.1-bullseye
    steps:
      - checkout
      - run:
          name: Build with GNU make
          command: make
      - run:
          name: Prepare coverage report for Codecov
          command: cp _output/coverage.out ./coverage.txt
      - run:
          name: Upload coverage to Codecov
          command: bash <(curl -s https://codecov.io/bash)

workflows:
  build:
    jobs:
      - build
