version: 2.1

jobs:
  build: 
    docker:
      - image: golang:1.17.1-bullseye
    steps:
      - checkout
      - run:
          name: Build with GNU make
          command: make

workflows:
  build:
    jobs:
      - build
