version: 2.1

jobs:
  build: 
    docker:
      - image: golangci/golangci-lint
      - image: mariadb:10.6
        environment:
          MYSQL_DATABASE: test
          MYSQL_PWD: root
          MARIADB_ROOT_PASSWORD: root
    steps:
      - checkout
      - run:
          name: Lint source code
          command: make lint
      - run:
          name: Run unit tests
          command: |
            make mysql.migrate.up
            make test
      - run:
          name: Build binary from source code
          command: make build
      - run:
          name: Upload coverage to Codecov
          command: bash <(curl -s https://codecov.io/bash)

workflows:
  build:
    jobs:
      - build
