version: 2.1

jobs:
  build: 
    docker:
      - image: golang:1.17.1-bullseye
    steps:
      - checkout
      - run:
          name: Lint source code
          command: make lint
      - run:
          name: Run unit tests
          command: make test
      - run:
          name: Build binary from source code
          command: make build
      - run:
          name: Upload coverage to Codecov
          command: bash <(curl -s https://codecov.io/bash)

workflows:
  build:
    jobs:
      - build
